FROM node:10

LABEL "com.github.actions.name"="echo"
LABEL "com.github.actions.description"="echo"
LABEL "com.github.actions.icon"="upload-cloud"
LABEL "com.github.actions.color"="green"

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
